#cloud-config
ssh_pwauth: no
users:
  - name: generalitalics
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEpHCfqI6ycdC23O3VURd8QpYPFggb/hnuTWlLMTpCjo generalitalics@mail.ru